name: Deploy to staging
on:
  push:
    branches: ["main"]

jobs:
  redeploy_website:
    name: Deploying the next project on staging
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{secrets.STAGING_SSH_KEY}}" &> ~/ssh_key
          mkdir .ssh
          echo "${{secrets.KNOWN_HOST}}" &> ~/.ssh/known_hosts
          ssh -i ~/ssh_key ubuntu@3.109.210.218
          cd EC2_next && git pull
          npm install
          npm run build
          pm2 restart hecka
